#!/usr/bin/env python3
"""Generate the desk's subagent roster and its per-agent slash commands from roster.json.

Thirty files are generated here rather than hand-written, for the same reason
scripts/generate-templates.py generates the Grok Bot templates: a roster is only coherent if
its lanes, parallelism caps and write scopes are maintained together, and thirty hand-edited
files drift apart within a week. roster.json is the single source of truth.

    python3 .claude/skills/desk-swarm/generate.py          # write
    python3 .claude/skills/desk-swarm/generate.py --check   # fail if the tree is stale

The roster is adapted from agent-swarm's `agents.json`, not copied. The upstream agent bodies
assume a runtime this repository does not have — `scripts/orch_plan.py`, a `.swarm/` task store,
a `yield` tool — and they know nothing about G-1 path ownership or G-2 receipts. Carrying them
over verbatim would produce fifteen agents that fail the desk's own gates on their first write.

Two rules are injected into every generated agent, and they are the point of this file:

G-1 INTERSECTION. A subagent inherits the ownership of the seat that spawned it. A05 Backend is
a backend engineer, but a backend engineer spawned by IOS may still only write under ios/. The
agent body therefore states the intersection rather than a fixed path list, because the correct
scope is not knowable at generation time — only at dispatch.

NON-INLINE DISPATCH. Every command tells the caller to dispatch through the Agent tool and not
to do the work in the main context. An agent that runs inline is not a subagent: it shares the
orchestrator's context window, it cannot run beside a sibling, and the parallelism the roster
declares (73 slots across 15 agents) collapses to one.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent.parent.parent  # .claude/skills/desk-swarm -> repo root
AGENTS_DIR = ROOT / ".claude" / "agents"
COMMANDS_DIR = ROOT / ".claude" / "commands"
BANNER = "<!-- generated by .claude/skills/desk-swarm/generate.py from roster.json — do not edit -->"

SCOPE_WRITER = """**Your write scope is the intersection of your lane and the spawning seat's owned paths.**
You are {name}, so your lane is {lane}. But ownership is enforced per seat by `ownership.yaml`
and G-1, and a subagent does not get its own ownership — it inherits the caller's. A backend
agent spawned by the iOS seat may write under `ios/` only. If the work you were given needs a
path outside that intersection, **stop and say so in your result**; do not write there and do
not widen your own scope. Cross-seat work goes through `docs/cross-bot-protocol.md`.

Check before writing, not after:

```sh
python3 ci/gates/check_ownership.py --bot <spawning-seat> --files <the files you intend to write>
```
"""

SCOPE_READER = """**You write nothing, so G-1 cannot fail on you — but your findings still have a scope.**
You are {name}, lane {lane}. Judge only what you were pointed at. A finding about a path the
spawning seat does not own is still worth reporting, but say so explicitly, because acting on it
needs a different seat and the cross-bot protocol in `docs/cross-bot-protocol.md`.

Verify ownership of what you are reviewing rather than assuming it:

```sh
python3 ci/gates/check_ownership.py --bot <spawning-seat> --files <the files under review>
```
"""

GOVERNANCE = """
## Desk governance — these bind you, not just the seat that spawned you

{scope}
**Evidence, not assertion (G-2).** Anything you claim must name the command that proves it.
Report the command, its exit code, and its output tail. If you did not run it, say the claim is
unverified — `ci/gates/check_receipt.py` rejects a receipt whose commands contain `--no-verify`,
`|| true`, `2>/dev/null`, `--force` or `--passWithNoTests`, so do not reach for those to make a
check pass.

**Never approve your own work.** G-2 fails when `approved_by` equals the bot that did the work.
You do not fill that field.

**Fail closed.** If the task needs a decision above your autonomy — a breaking contract change,
a destructive operation, a secret, a release — stop and report what you need. Do not proceed on
an assumption and do not pick the option that merely unblocks you.
"""

RESULT_FORMAT = """
## Report back in this shape

Your caller cannot see your context. Everything that matters has to be in the result:

```
STATE: IN_REVIEW | FAILED | BLOCKED
SUMMARY: one or two sentences on what changed and why
FILES: each path you wrote, with one clause on what changed in it
COMMANDS: each command you ran, its exit code, and the last line of its output
UNVERIFIED: anything you could not prove, and what proving it would take
NEEDS: (BLOCKED only) the input, decision or permission you are waiting on
```

`IN_REVIEW`, never `DONE`. You do not get to call your own work complete — a reviewing seat does.
"""


def agent_md(a: dict) -> str:
    ro = a["read_only"]
    scope = (
        "You are read-only. You have no Write or Edit tool, by design: a gate that can edit the "
        "code it judges is not a gate. Report findings; let an implementing agent act on them."
        if ro
        else "Write only inside the intersection described below. Never edit another agent's output "
        "concurrently — the orchestrator assigns non-overlapping files for exactly this reason."
    )
    return f"""---
name: {a["slug"]}
description: "{a["code"]} ({a["id"]}) — {a["description"]} Runs as a subagent; never inline."
tools: {", ".join(a["tools"])}
model: {a["model"]}
---

{BANNER}

# {a["id"]} {a["code"]} — {a["name"]}

**Lane:** {a["lane"]} · **Class:** {a["class"]} · **Concurrency cap:** {a["max_parallel"]} · **Model:** {a["model"]}

{a["description"]}

**Capabilities:** {", ".join(a["capabilities"])}

{scope}

## Scope discipline

You were given a bounded task: specific files, a specific acceptance condition, and a verify
command. Stay inside it. If you discover work beyond that boundary — a refactor that would help,
a bug in a neighbouring module — **report it, do not do it**. The orchestrator fanned several
agents out across non-overlapping files, and an agent that wanders outside its assignment
collides with a sibling it cannot see.
{GOVERNANCE.format(scope=(SCOPE_READER if ro else SCOPE_WRITER).format(name=a["name"], lane=a["lane"]))}{RESULT_FORMAT}"""


def command_md(a: dict) -> str:
    return f"""---
name: desk-{a["code"].lower()}
description: Dispatch {a["id"]} {a["code"]} ({a["name"]}) as a parallel subagent
disable-model-invocation: true
---

{BANNER}

Dispatch **{a["id"]} {a["code"]} — {a["name"]}** for: $ARGUMENTS

**Do not do this work yourself.** Invoke the Agent tool with `subagent_type: "{a["slug"]}"` and
let it run there. Running it in this context defeats the point: it would consume the
orchestrator's context window, and it could not run beside a sibling agent.

Give it, in the prompt:

1. **The task**, as a single outcome — not a list of steps to copy.
2. **The spawning seat**, by name (`bot-00-programming-lead` … `bot-06-quality-security`). It
   needs this to know its write scope; without it, it cannot run the G-1 check and will guess.
3. **Bounded files** it may write. Non-overlapping with any other agent dispatched in the same
   message.
4. **The verify command** that decides whether it succeeded.
5. **Acceptance**: what must be true when it is finished.

Concurrency cap for this agent is **{a["max_parallel"]}**. To run it alongside others, put every
Agent call in **one** message — calls in separate messages run one after another, which is the
inline behaviour this command exists to avoid. `/desk-swarm` does that fan-out for you.
"""


SWARM_CMD = """---
name: desk-swarm
description: Fan several desk subagents out in parallel across non-overlapping files
disable-model-invocation: true
---

{banner}

Fan the swarm out for: $ARGUMENTS

## The one rule that makes this parallel

**Put every Agent call in a single message.** Tool calls in one message run concurrently; calls
spread across messages run one after another. That is the whole difference between a swarm and a
queue, and it is the thing most easily lost — if you find yourself dispatching one agent, reading
its result, then dispatching the next, you have built a sequential pipeline with extra steps.

## Before dispatching

1. **Split the work by lane, not by file count.** {lanes}
2. **Assign non-overlapping files.** Two agents editing one file is a lost write; the loser does
   not know it lost. If two pieces of work genuinely need the same file, they are one task.
3. **Name the spawning seat in every prompt.** Each agent needs it for its own G-1 check.
4. **Give each one a verify command.** An agent with no verify command cannot tell you whether it
   worked, and will report success on the basis of having finished.
5. **Respect the caps.** Per-agent caps are in `roster.json`; keep the total in flight modest —
   four concurrent is the figure the upstream swarm skill settles on, and context, not the cap,
   is usually the real limit.

## Roster

| Command | Agent | Lane | Cap | Writes |
|---|---|---|---|---|
{table}

## After they return

**You verify on the tree.** Every agent reports `IN_REVIEW`, never `DONE` — none of them may
call its own work complete. Run the verify commands yourself, check the files they claim to have
written actually changed, and run the gates:

```sh
python3 ci/gates/check_ownership.py --bot <seat> --files <all files touched>
python3 ci/gates/check_secrets.py --files <all files touched>
```

Then write **one** receipt for the whole fan-out under `.receipts/<seat>/`, listing each agent's
commands as evidence. Remember `.receipts/**/*.json` is gitignored — it needs `git add -f`.

Anything an agent returned as `UNVERIFIED` goes into the receipt's `unverified` list. Do not
quietly promote it to a claim because the tests happened to pass.
"""


def build() -> dict[Path, str]:
    roster = json.loads((HERE / "roster.json").read_text())
    agents = roster["agents"]
    files: dict[Path, str] = {}
    for a in agents:
        files[AGENTS_DIR / f"{a['slug']}.md"] = agent_md(a)
        files[COMMANDS_DIR / f"desk-{a['code'].lower()}.md"] = command_md(a)

    lanes: dict[str, list[str]] = {}
    for a in agents:
        lanes.setdefault(a["lane"], []).append(a["code"])
    lane_text = " ".join(
        f"**{lane}**: {', '.join(codes)}." for lane, codes in lanes.items()
    )
    table = "\n".join(
        f"| `/desk-{a['code'].lower()}` | {a['id']} {a['name']} | {a['lane']} | {a['max_parallel']} | "
        f"{'read-only' if a['read_only'] else 'yes'} |"
        for a in agents
    )
    files[COMMANDS_DIR / "desk-swarm.md"] = SWARM_CMD.format(
        banner=BANNER, lanes=lane_text, table=table
    )
    return files


def main(argv: list[str]) -> int:
    files = build()
    check = "--check" in argv
    stale = [p for p, body in files.items() if not p.exists() or p.read_text() != body]
    if check:
        for p in stale:
            print(f"STALE {p.relative_to(ROOT)}")
        print(f"{len(files)} generated file(s), {len(stale)} stale")
        return 1 if stale else 0
    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    COMMANDS_DIR.mkdir(parents=True, exist_ok=True)
    for p, body in files.items():
        p.write_text(body, encoding="utf-8")
    print(f"wrote {len(files)} file(s): {len(files) - 1} agents+commands pairs plus desk-swarm")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
